import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Link, useNavigate } from 'react-router-dom';
import { register as registerApi } from '../../api/auth.api';
import Input from '../../components/common/Input';
import Select from '../../components/common/Select';
import Button from '../../components/common/Button';
import toast from 'react-hot-toast';

const schema=z.object({name:z.string().trim().min(2,'Name must contain at least 2 characters'),email:z.string().trim().email('Enter a valid email address'),password:z.string().min(8,'Use at least 8 characters').regex(/[A-Z]/,'Add an uppercase letter').regex(/[a-z]/,'Add a lowercase letter').regex(/[0-9]/,'Add a number'),confirm:z.string(),role:z.enum(['ADMIN','MEMBER'])}).refine(x=>x.password===x.confirm,{path:['confirm'],message:'Passwords do not match'});
type Form=z.infer<typeof schema>;
export default function Register(){const nav=useNavigate();const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm<Form>({resolver:zodResolver(schema),defaultValues:{role:'MEMBER'}});const submit=async(d:Form)=>{try{await registerApi({name:d.name,email:d.email,password:d.password,role:d.role});toast.success('Account created');nav('/login',{replace:true})}catch(e:any){toast.error(e?.response?.data?.message||'Registration failed. Please try again.')}};return <div className="grid min-h-screen place-items-center bg-slate-950 p-4"><form noValidate onSubmit={handleSubmit(submit)} className="w-full max-w-md rounded-3xl bg-white p-8 shadow-2xl" aria-labelledby="register-title"><div className="mb-6"><div className="text-2xl font-black text-brand-600">TeamFlow</div><h1 id="register-title" className="mt-3 text-2xl font-bold">Create account</h1></div><div className="space-y-4"><Input label="Name" autoComplete="name" {...register('name')} error={errors.name?.message}/><Input label="Email" type="email" autoComplete="email" {...register('email')} error={errors.email?.message}/><Input label="Password" type="password" autoComplete="new-password" {...register('password')} error={errors.password?.message}/><Input label="Confirm password" type="password" autoComplete="new-password" {...register('confirm')} error={errors.confirm?.message}/><Select label="Role" {...register('role')} error={errors.role?.message}><option value="MEMBER">Member</option><option value="ADMIN">Admin</option></Select><p className="text-xs text-slate-500">Password: 8+ characters, uppercase, lowercase and number.</p><Button type="submit" loading={isSubmitting} className="w-full bg-brand-600 text-white">Create account</Button></div><p className="mt-5 text-center text-sm text-slate-500">Already registered? <Link className="font-semibold text-brand-600" to="/login">Sign in</Link></p></form></div>}
